CostPilot.Web/Controllers/CostRequestController.cs
using Microsoft.AspNetCore.Mvc;

using CostPilot.Services.Core.Contracts;
using CostPilot.ViewModels.CostRequest;
using static CostPilot.Common.ValidationErrorMessages;
using static CostPilot.Common.ApplicationConstants;
using Microsoft.AspNetCore.Authorization;

namespace CostPilot.Web.Controllers
{
    public class CostRequestController : BaseUserController
    {
        private readonly ICostCenterService costCenterService;
        private readonly ICostCurrencyService costCurrencyService;
        private readonly ICostTypeService costTypeService;
        private readonly ICostRequestService costRequestService;

        public CostRequestController(ICostCenterService costCenterService, 
            ICostCurrencyService costCurrencyService,
            ICostTypeService costTypeService,
            ICostRequestService costRequestService)
        {
            this.costCenterService = costCenterService;
            this.costCurrencyService = costCurrencyService;
            this.costTypeService = costTypeService;
            this.costRequestService = costRequestService;
        }

        [HttpGet]
        public async Task<IActionResult> Create()
        {
			try
			{
                var model = new CostRequestCreateInputModel();
                model.Centers = await this.costCenterService.GetActiveCostCentersAsync();
                model.Currencies = await this.costCurrencyService.GetActiveCostCurrenciesAsync();
                model.Types = await costTypeService.GetActiveCostTypesAsync();
                return this.View(model);
			}
            catch (Exception e)
            {
                Console.WriteLine(e.Message);
                return this.ExceptionCatchRedirect();
            }
        }

        [HttpPost]
        public async Task<IActionResult> Create(CostRequestCreateInputModel model)
        {
            try
            {
                var costRequestAmount = 0.0m;
                var isAmountValid = decimal.TryParse(model.Amount, out costRequestAmount) == true && costRequestAmount > 0.0m;
                if (isAmountValid == false)
                {
                    this.ModelState.AddModelError(nameof(model.Amount), "Invalid Amount");   
                }

                if (this.ModelState.IsValid == false)
                {
                    model.Centers = await this.costCenterService.GetActiveCostCentersAsync();
                    model.Currencies = await this.costCurrencyService.GetActiveCostCurrenciesAsync();
                    model.Types = await costTypeService.GetActiveCostTypesAsync();
                    return this.View(model);
                }

                var userId = this.GetUserId();
                var createResult = await this.costRequestService.CreateCostRequestAsync(model, costRequestAmount, userId);
                if (createResult == false)
                {
                    this.ModelState.AddModelError(string.Empty, CreateEditOverallErrorMessage);
                    model.Centers = await this.costCenterService.GetActiveCostCentersAsync();
                    model.Currencies = await this.costCurrencyService.GetActiveCostCurrenciesAsync();
                    model.Types = await costTypeService.GetActiveCostTypesAsync();
                    return this.View(model);
                }

                return this.RedirectToAction(nameof(Index));
            }
            catch (Exception e)
            {
                Console.WriteLine(e.Message);
                return this.ExceptionCatchRedirect();
            }
        }

        [HttpGet]
        public async Task<IActionResult> Index(string? searchNumber, string? searchCurrency, string? searchStatus)
        {
            try
            {
                var userId = this.GetUserId();
                var model = await this.costRequestService.GetMyCostRequestsAsync(userId, searchNumber, searchCurrency, searchStatus);
                return this.View(model);
            }
            catch (Exception e)
            {
                Console.WriteLine(e.Message);
                return this.ExceptionCatchRedirect();
            }
        }

        [HttpGet]
        public async Task<IActionResult> Details(string? id)
        {
            try
            {
                var model = await this.costRequestService.GetCostRequestDetailsAsync(id);
                if (model == null)
                {
                    this.Response.StatusCode = 400;
                    return this.View(PathToBadRequestView);
                }

                return this.View(model);
            }
            catch (Exception e)
            {
                Console.WriteLine(e.Message);
                return this.ExceptionCatchRedirect();
            }
        }

        [HttpGet]
        public async Task<IActionResult> Cancel(string? id)
        {
            try
            {
                var userId = this.GetUserId();
                var cancelResult = await this.costRequestService.CancelCostRequestAsync(id, userId);
                if (cancelResult == false)
                {
                    this.Response.StatusCode = 400;
                    return this.View(PathToBadRequestView);
                }

                return this.RedirectToAction(nameof(Index));
            }
            catch (Exception e)
            {
                Console.WriteLine(e.Message);
                return this.ExceptionCatchRedirect();
            }
        }

        [HttpGet]
        public async Task<IActionResult> Edit(string? id)
        {
            try
            {
                var userId = this.GetUserId();
                var model = await this.costRequestService.GetCostRequestForEditAsync(id, userId);
                if (model == null)
                {
                    this.Response.StatusCode = 400;
                    return this.View(PathToBadRequestView);
                }

                model.Centers = await this.costCenterService.GetActiveCostCentersAsync();
                model.Currencies = await this.costCurrencyService.GetActiveCostCurrenciesAsync();
                model.Types = await costTypeService.GetActiveCostTypesAsync();
                return this.View(model);
            }
            catch (Exception e)
            {
                Console.WriteLine(e.Message);
                return this.ExceptionCatchRedirect();
            }
        }

        [HttpPost]
        public async Task<IActionResult> Edit(CostRequestEditInputModel model)
        {
            try
            {
                var costRequestAmount = 0.0m;
                var isAmountValid = decimal.TryParse(model.Amount, out costRequestAmount) == true && costRequestAmount > 0.0m;
                if (isAmountValid == false)
                {
                    this.ModelState.AddModelError(nameof(model.Amount), "Invalid Amount");
                }

                if (this.ModelState.IsValid == false)
                {
                    model.Centers = await this.costCenterService.GetActiveCostCentersAsync();
                    model.Currencies = await this.costCurrencyService.GetActiveCostCurrenciesAsync();
                    model.Types = await costTypeService.GetActiveCostTypesAsync();
                    return this.View(model);
                }

                var userId = this.GetUserId();
                var editResult = await this.costRequestService.EditCostRequestAsync(model, costRequestAmount, userId);
                if (editResult == false)
                {
                    this.ModelState.AddModelError(string.Empty, CreateEditOverallErrorMessage);
                    model.Centers = await this.costCenterService.GetActiveCostCentersAsync();
                    model.Currencies = await this.costCurrencyService.GetActiveCostCurrenciesAsync();
                    model.Types = await costTypeService.GetActiveCostTypesAsync();
                    return this.View(model);
                }

                return this.RedirectToAction(nameof(Index));
            }
            catch (Exception e)
            {
                Console.WriteLine(e.Message);
                return this.ExceptionCatchRedirect();
            }
        }

        [HttpGet]
        public async Task<IActionResult> ForApproval()
        {
            try
            {
                var userId = this.GetUserId();
                var model = await this.costRequestService.GetCostRequestsForApprovalAsync(userId);
                return this.View(model);
            }
            catch (Exception e)
            {
                Console.WriteLine(e.Message);
                return this.ExceptionCatchRedirect();
            }
        }

        [HttpGet]
        public async Task<IActionResult> Approve(string? id)
        {
            try
            {
                var userId = this.GetUserId();
                var model = await this.costRequestService.GetCostRequestForDecisionAsync(id, userId);
                if (model == null)
                {
                    this.Response.StatusCode = 400;
                    return this.View(PathToBadRequestView);
                }

                return this.View(model);
            }
            catch (Exception e)
            {
                Console.WriteLine(e.Message);
                return this.ExceptionCatchRedirect();
            }
        }

        [HttpPost]
        public async Task<IActionResult> ConfirmApprove(CostRequestDecisionInputModel model)
        {
            try
            {
                var userId = this.GetUserId();
                var approveResult = await this.costRequestService.ApproveCostRequestAsync(model, userId);
                if (approveResult == false)
                {
                    this.ModelState.AddModelError(string.Empty, CreateEditOverallErrorMessage);
                    return this.View(model);
                }

                return this.RedirectToAction(nameof(ForApproval));
            }

CostPilot.Web/Views/CostRequest/AfterDecision.cshtml
@using CostPilot.ViewModels.CostRequest
@model IEnumerable<CostRequestAfterDecisionViewModel>

@{
    ViewData["Title"] = "Approval History";
}

<h2 class="text-center">@ViewData["Title"]</h2>
<hr />

<div class="row">
    <div class="col-sm-12">
        <form asp-controller="CostRequest" asp-action="AfterDecision" method="get">
            <div class="row">
                <div class="col-sm-2 mb-2">
                    <input type="text" class="form-control" name="searchNumber" placeholder="Search by number" />
                </div>
                <div class="col-sm-2 mb-2">
                    <input type="text" class="form-control" name="searchCurrency" placeholder="Search by currency" />
                </div>
                <div class="col-sm-2 mb-2">
                    <input type="text" class="form-control" name="searchStatus" placeholder="Search by status" />
                </div>
                <div class="col-sm-3 mb-2">
                    <button type="submit" class="btn btn-success btn-dark-text w-100 fw-bold rounded">
                        <i class="fa-solid fa-magnifying-glass"></i> Search
                    </button>
                </div>
                <div class="col-sm-3 mb-2">
                    <a asp-controller="CostRequest" asp-action="AfterDecision" class="btn btn-secondary btn-dark-text w-100 fw-bold rounded">
                        <i class="fa-solid fa-rotate-right"></i> Reset
                    </a>
                </div>
            </div>
        </form>
    </div>
</div>

@if (Model == null || Model.Any() == false)
{
    <div class="text-center mt-5">
        <h4>There are still no cost requests approved/rejected by you</h4>
    </div>
}
else
{
    <div class="table-responsive" style="max-height: 400px; overflow-y: auto;">
        <table class="table table-striped">
            <thead>
                <tr>
                    <th style="position: sticky; top: 0; background-color: darkslategrey; z-index: 1;">Number</th>
                    <th style="position: sticky; top: 0; background-color: darkslategrey; z-index: 1;">Submitted On</th>
                    <th style="position: sticky; top: 0; background-color: darkslategrey; z-index: 1;">Amount</th>
                    <th style="position: sticky; top: 0; background-color: darkslategrey; z-index: 1;">Currency</th>
                    <th style="position: sticky; top: 0; background-color: darkslategrey; z-index: 1;">Status</th>
                    <th style="position: sticky; top: 0; background-color: darkslategrey; z-index: 1;">Actions</th>
                </tr>
            </thead>
            <tbody>
                @foreach (var costRequest in Model)
                {
                    <tr>
                        <td>@costRequest.Number</td>
                        <td>@costRequest.SubmittedOn</td>
                        <td>@costRequest.Amount</td>
                        <td>@costRequest.Currency</td>
                        <td>@costRequest.Status</td>
                        <td>
                            <a asp-controller="CostRequest" asp-action="Details" asp-route-id="@costRequest.Id" class="btn btn-sm btn-light">Details</a>
                        </td>
                    </tr>
                }
            </tbody>
        </table>
    </div>
}

CostPilot.Web/Views/CostRequest/Approve.cshtml
@using CostPilot.ViewModels.CostRequest
@model CostRequestDecisionInputModel

@{
    ViewData["Title"] = "Approve Cost Request";
}

<h2 class="text-center">@ViewData["Title"] @Model.Number</h2>
<hr />

<div asp-validation-summary="ModelOnly" class="validation-summary-errors text-danger text-center"></div>

<div class="row">
    <div class="col-sm-12 offset-lg-2 col-lg-8 offset-xl-3 col-xl-6">
        <form asp-controller="CostRequest" asp-action="ConfirmApprove" method="post">
            <input type="hidden" asp-for="@Model.Id" />

            <div class="mb-2">
                <label asp-for="@Model.Comment" class="form-label-add-edit">Comment</label>
                <textarea asp-for="@Model.Comment" class="form-control" aria-required="true" rows="3"></textarea>
            </div>

            <div class="mb-2">
                <button type="submit" class="btn btn-success btn-dark-text w-100 py-2 fw-bold rounded">
                    <i class="fa-solid fa-thumbs-up"></i> Confirm Approve
                </button>
            </div>
        </form>

        <div class="mb-2">
            <a asp-controller="CostRequest" asp-action="ForApproval" class="btn btn-secondary btn-dark-text w-100 py-2 fw-bold rounded">
                <i class="fa-solid fa-xmark"></i> Cancel
            </a>
        </div>
    </div>
</div>

CostPilot.Web/Views/CostRequest/Create.cshtml
@using CostPilot.ViewModels.CostRequest
@model CostRequestCreateInputModel

@{
    ViewData["Title"] = "Create New Cost Request";
}

<h2 class="text-center">@ViewData["Title"]</h2>
<hr />

<div asp-validation-summary="ModelOnly" class="validation-summary-errors text-danger text-center"></div>

<div class="row">
    <div class="col-sm-12 offset-lg-2 col-lg-8 offset-xl-3 col-xl-6">
        <form asp-controller="CostRequest" asp-action="Create" method="post">
            <div class="row">
                <div class="col-sm-6 mb-2">
                    <label asp-for="@Model.Amount" class="form-label-add-edit">Amount</label>
                    <input asp-for="@Model.Amount" type="number" step="0.01" min="0" class="form-control" aria-required="true" placeholder="0.00" />
                    <span asp-validation-for="@Model.Amount" class="text-danger"></span>
                </div>

                <div class="col-sm-6 mb-2">
                    <label asp-for="@Model.CurrencyId" class="form-label-add-edit">Currency</label>
                    <select asp-for="@Model.CurrencyId" class="form-control" aria-required="true" asp-items="@(new SelectList(Model.Currencies, "Id", "Code"))">
                        <option value="">...</option>
                    </select>
                    <span asp-validation-for="@Model.CurrencyId" class="text-danger"></span>
                </div>
            </div>

            <div class="mb-2">
                <label asp-for="@Model.TypeId" class="form-label-add-edit">Cost Type</label>
                <select asp-for="@Model.TypeId" class="form-control" aria-required="true" asp-items="@(new SelectList(Model.Types, "Id", "Description"))">
                    <option value="">...</option>
                </select>
                <span asp-validation-for="@Model.TypeId" class="text-danger"></span>
            </div>

            <div class="mb-2">
                <label asp-for="@Model.CenterId" class="form-label-add-edit">Cost Center</label>
                <select asp-for="@Model.CenterId" class="form-control" aria-required="true" asp-items="@(new SelectList(Model.Centers, "Id", "CodeDescription"))">
                    <option value="">...</option>
                </select>
                <span asp-validation-for="@Model.CenterId" class="text-danger"></span>
            </div>

            <div class="mb-2">
                <label asp-for="@Model.BriefDescription" class="form-label-add-edit">Brief Description</label>
                <textarea asp-for="@Model.BriefDescription" class="form-control" aria-required="true" rows="2" placeholder="Please enter cost request brief description"></textarea>
                <span asp-validation-for="@Model.BriefDescription" class="text-danger"></span>
            </div>

            <div class="mb-2">
                <label asp-for="@Model.DetailedDescription" class="form-label-add-edit">Detailed Description</label>
                <textarea asp-for="@Model.DetailedDescription" class="form-control" aria-required="true" rows="3" placeholder="Please enter cost request detailed description"></textarea>
                <span asp-validation-for="@Model.DetailedDescription" class="text-danger"></span>
            </div>

            <div class="mb-2">
                <button class="btn btn-success btn-dark-text w-100 py-2 fw-bold rounded" type="submit">
                    <i class="fas fa-save"></i> Save
                </button>
            </div>
        </form>

        <div class="mb-2">
            <a asp-controller="CostRequest" asp-action="Index" class="btn btn-secondary btn-dark-text w-100 py-2 fw-bold rounded">
                <i class="fa-solid fa-xmark"></i> Cancel
            </a>
        </div>
    </div>
</div>

CostPilot.Web/Views/CostRequest/Edit.cshtml
@using CostPilot.ViewModels.CostRequest
@model CostRequestEditInputModel

@{
    ViewData["Title"] = "Edit Cost Request";
}

<h2 class="text-center">@ViewData["Title"]</h2>
<hr />

<div asp-validation-summary="ModelOnly" class="validation-summary-errors text-danger text-center"></div>

<div class="row">
    <div class="col-sm-12 offset-lg-2 col-lg-8 offset-xl-3 col-xl-6">
        <form asp-controller="CostRequest" asp-action="Edit" method="post">
            <input type="hidden" asp-for="@Model.Id" />

            <div class="row">
                <div class="col-sm-6 mb-2">
                    <label asp-for="@Model.Amount" class="form-label-add-edit">Amount</label>
                    <input asp-for="@Model.Amount" type="number" step="0.01" min="0" class="form-control" aria-required="true" placeholder="0.00" />
                    <span asp-validation-for="@Model.Amount" class="text-danger"></span>
                </div>

                <div class="col-sm-6 mb-2">
                    <label asp-for="@Model.CurrencyId" class="form-label-add-edit">Currency</label>
                    <select asp-for="@Model.CurrencyId" class="form-control" aria-required="true" asp-items="@(new SelectList(Model.Currencies, "Id", "Code"))">
                        <option value="">...</option>
                    </select>
                    <span asp-validation-for="@Model.CurrencyId" class="text-danger"></span>
                </div>
            </div>

            <div class="mb-2">
                <label asp-for="@Model.TypeId" class="form-label-add-edit">Cost Type</label>
                <select asp-for="@Model.TypeId" class="form-control" aria-required="true" asp-items="@(new SelectList(Model.Types, "Id", "Description"))">
                    <option value="">...</option>
                </select>
                <span asp-validation-for="@Model.TypeId" class="text-danger"></span>
            </div>

            <div class="mb-2">
                <label asp-for="@Model.CenterId" class="form-label-add-edit">Cost Center</label>
                <select asp-for="@Model.CenterId" class="form-control" aria-required="true" asp-items="@(new SelectList(Model.Centers, "Id", "CodeDescription"))">
                    <option value="">...</option>
                </select>
                <span asp-validation-for="@Model.CenterId" class="text-danger"></span>
            </div>

            <div class="mb-2">
                <label asp-for="@Model.BriefDescription" class="form-label-add-edit">Brief Description</label>
                <textarea asp-for="@Model.BriefDescription" class="form-control" aria-required="true" rows="2" placeholder="Please enter cost request brief description"></textarea>
                <span asp-validation-for="@Model.BriefDescription" class="text-danger"></span>
            </div>

            <div class="mb-2">
                <label asp-for="@Model.DetailedDescription" class="form-label-add-edit">Detailed Description</label>
                <textarea asp-for="@Model.DetailedDescription" class="form-control" aria-required="true" rows="3" placeholder="Please enter cost request detailed description"></textarea>
                <span asp-validation-for="@Model.DetailedDescription" class="text-danger"></span>
            </div>

            <div class="mb-2">
                <button class="btn btn-success btn-dark-text w-100 py-2 fw-bold rounded" type="submit">
                    <i class="fas fa-save"></i> Update
                </button>
            </div>
        </form>

        <div class="mb-2">
            <a asp-controller="CostRequest" asp-action="Index" class="btn btn-secondary btn-dark-text w-100 py-2 fw-bold rounded">
                <i class="fa-solid fa-xmark"></i> Cancel
            </a>
        </div>
    </div>
</div>

CostPilot.Web/Views/CostRequest/ForApproval.cshtml
@using CostPilot.ViewModels.CostRequest
@model IEnumerable<CostRequestForApprovalViewModel>

@{
    ViewData["Title"] = "Cost Requests For Approval";
}

<h2 class="text-center">@ViewData["Title"]</h2>
<hr />

@if (Model == null || Model.Any() == false)
{
    <div class="text-center mt-5">
        <h4>There are no cost requests submitted to you for approval</h4>
    </div>
}
else
{
    <div class="table-responsive" style="max-height: 400px; overflow-y: auto;">
        <table class="table table-striped">
            <thead>
                <tr>
                    <th style="position: sticky; top: 0; background-color: darkslategrey; z-index: 1;">Number</th>
                    <th style="position: sticky; top: 0; background-color: darkslategrey; z-index: 1;">Submitted On</th>
                    <th style="position: sticky; top: 0; background-color: darkslategrey; z-index: 1;">Amount</th>
                    <th style="position: sticky; top: 0; background-color: darkslategrey; z-index: 1;">Currency</th>
                    <th style="position: sticky; top: 0; background-color: darkslategrey; z-index: 1;">Brief Description</th>
                    <th style="position: sticky; top: 0; background-color: darkslategrey; z-index: 1;">Actions</th>
                </tr>
            </thead>
            <tbody>
                @foreach (var costRequest in Model)
                {
                    <tr>
                        <td>@costRequest.Number</td>
                        <td>@costRequest.SubmittedOn</td>
                        <td>@costRequest.Amount</td>
                        <td>@costRequest.Currency</td>
                        <td>@costRequest.BriefDescription</td>
                        <td>
                            <a asp-controller="CostRequest" asp-action="Details" asp-route-id="@costRequest.Id" class="btn btn-sm btn-light">Details</a>
                            <a asp-controller="CostRequest" asp-action="Approve" asp-route-id="@costRequest.Id" class="btn btn-sm btn-success">Approve</a>
                            <a asp-controller="CostRequest" asp-action="Reject" asp-route-id="@costRequest.Id" class="btn btn-sm btn-danger">Reject</a>
                        </td>
                    </tr>
                }
            </tbody>
        </table>
    </div>
}

CostPilot.Web/Views/CostRequest/Index.cshtml
@using CostPilot.ViewModels.CostRequest
@model IEnumerable<CostRequestIndexViewModel>

@{
    ViewData["Title"] = "My Cost Requests";
}

<h2 class="text-center">@ViewData["Title"]</h2>
<hr />

<div class="row">
    <div class="col-sm-12">
        <form asp-controller="CostRequest" asp-action="Index" method="get">
            <div class="row">
                <div class="col-sm-2 mb-2">
                    <input type="text" class="form-control" name="searchNumber" placeholder="Search by number" />
                </div>
                <div class="col-sm-2 mb-2">
                    <input type="text" class="form-control" name="searchCurrency" placeholder="Search by currency" />
                </div>
                <div class="col-sm-2 mb-2">
                    <input type="text" class="form-control" name="searchStatus" placeholder="Search by status" />
                </div>
                <div class="col-sm-3 mb-2">
                    <button type="submit" class="btn btn-success btn-dark-text w-100 fw-bold rounded">
                        <i class="fa-solid fa-magnifying-glass"></i> Search
                    </button>
                </div>
                <div class="col-sm-3 mb-2">
                    <a asp-controller="CostRequest" asp-action="Index" class="btn btn-secondary btn-dark-text w-100 fw-bold rounded">
                        <i class="fa-solid fa-rotate-right"></i> Reset
                    </a>
                </div>
            </div>
        </form>
    </div>
</div>

@if (Model == null || Model.Any() == false)
{
    <div class="text-center mt-5">
        <h4>You don't have any cost requests submitted yet!</h4>
        <p class="text-muted">Start creating and save your cost requests.</p>
    </div>
}
else
{
    <div class="table-responsive" style="max-height: 400px; overflow-y: auto;">
        <table class="table table-striped">
            <thead>
                <tr>
                    <th style="position: sticky; top: 0; background-color: darkslategrey; z-index: 1;">Number</th>
                    <th style="position: sticky; top: 0; background-color: darkslategrey; z-index: 1;">Submitted On</th>
                    <th style="position: sticky; top: 0; background-color: darkslategrey; z-index: 1;">Amount</th>
                    <th style="position: sticky; top: 0; background-color: darkslategrey; z-index: 1;">Currency</th>
                    <th style="position: sticky; top: 0; background-color: darkslategrey; z-index: 1;">Status</th>
                    <th style="position: sticky; top: 0; background-color: darkslategrey; z-index: 1;">Approver</th>
                    <th style="position: sticky; top: 0; background-color: darkslategrey; z-index: 1;">Actions</th>
                </tr>
            </thead>
            <tbody>
                @foreach (var costRequest in Model)
                {
                    <tr>
                        <td>@costRequest.Number</td>
                        <td>@costRequest.SubmittedOn</td>
                        <td>@costRequest.Amount</td>
                        <td>@costRequest.Currency</td>
                        <td>@costRequest.Status</td>
                        <td>@costRequest.ApproverFullName</td>
                        @if (costRequest.IsApprovedOrRejected == true)
                        {
                            <td>
                                <a asp-controller="CostRequest" asp-action="Details" asp-route-id="@costRequest.Id" class="btn btn-sm btn-light">Details</a>
                            </td>
                        }
                        else
                        {
                            <td>
                                <a asp-controller="CostRequest" asp-action="Edit" asp-route-id="@costRequest.Id" class="btn btn-sm btn-primary">Edit</a>
                                <a asp-controller="CostRequest" asp-action="Cancel" asp-route-id="@costRequest.Id" class="btn btn-sm btn-danger">Cancel</a>
                                <a asp-controller="CostRequest" asp-action="Details" asp-route-id="@costRequest.Id" class="btn btn-sm btn-light">Details</a>
                            </td>
                        }
                    </tr>
                }
            </tbody>
        </table>
    </div>
}

CostPilot.Web/Views/CostRequest/Reject.cshtml
@using CostPilot.ViewModels.CostRequest
@model CostRequestDecisionInputModel

@{
    ViewData["Title"] = "Reject Cost Request";
}

<h2 class="text-center">@ViewData["Title"] @Model.Number</h2>
<hr />

<div asp-validation-summary="ModelOnly" class="validation-summary-errors text-danger text-center"></div>

<div class="row">
    <div class="col-sm-12 offset-lg-2 col-lg-8 offset-xl-3 col-xl-6">
        <form asp-controller="CostRequest" asp-action="ConfirmReject" method="post">
            <input type="hidden" asp-for="@Model.Id" />

            <div class="mb-2">
                <label asp-for="@Model.Comment" class="form-label-add-edit">Comment</label>
                <textarea asp-for="@Model.Comment" class="form-control" aria-required="true" rows="3"></textarea>
            </div>

            <div class="mb-2">
                <button type="submit" class="btn btn-success btn-dark-text w-100 py-2 fw-bold rounded">
                    <i class="fa-solid fa-thumbs-down"></i> Confirm Reject
                </button>
            </div>
        </form>

        <div class="mb-2">
            <a asp-controller="CostRequest" asp-action="ForApproval" class="btn btn-secondary btn-dark-text w-100 py-2 fw-bold rounded">
                <i class="fa-solid fa-xmark"></i> Cancel
            </a>
        </div>
    </div>
</div>