CostPilot.Web/Controllers/CostCenterController.cs
using Microsoft.AspNetCore.Mvc;

using CostPilot.Services.Core.Contracts;
using CostPilot.ViewModels.CostCenter;
using static CostPilot.Common.ApplicationConstants;
using static CostPilot.Common.ValidationErrorMessages;

namespace CostPilot.Web.Controllers
{
    public class CostCenterController : BaseAdminController
    {
        private readonly ICostCenterService costCenterService;
        private readonly IUserService userService;

        public CostCenterController(ICostCenterService costCenterService, IUserService userService)
        {
            this.costCenterService = costCenterService;
            this.userService = userService;
        }

        [HttpGet]
        public async Task<IActionResult> Index()
        {
            try
            {
                var model = await this.costCenterService.GetCostCentersAsync();
                return this.View(model);
            }
            catch (Exception e)
            {
                Console.WriteLine(e.Message);
                return this.ExceptionCatchRedirect();
            }
        }

        [HttpGet]
        public async Task<IActionResult> Create()
        {
            try
            {
                var model = new CostCenterCreateInputModel();
                model.Owners = await this.userService.GetUserDetailsAsync();
                return this.View(model);
            }
            catch (Exception e)
            {
                Console.WriteLine(e.Message);
                return this.ExceptionCatchRedirect();
            }
            
        }

        [HttpPost]
        public async Task<IActionResult> Create(CostCenterCreateInputModel model)
        {
            try
            {
                if (this.ModelState.IsValid == false)
                {
                    model.Owners = await this.userService.GetUserDetailsAsync();
                    return this.View(model);
                }

                var createResult = await this.costCenterService.CreateCostCenterAsync(model);
                if (createResult == false)
                {
                    this.ModelState.AddModelError(string.Empty, CreateEditOverallErrorMessage);
                    model.Owners = await this.userService.GetUserDetailsAsync();
                    return this.View(model);
                }

                return this.RedirectToAction(nameof(Index));
            }
            catch (Exception e)
            {
                Console.WriteLine(e.Message);
                return this.ExceptionCatchRedirect();
            }
        }

        [HttpGet]
        public async Task<IActionResult> Disable(string? id)
        {
            try
            {
                var disableResult = await this.costCenterService.DisableCostCenterAsync(id);
                if (disableResult == false) 
                {
                    this.Response.StatusCode = 400;
                    return this.View(PathToBadRequestView);
                }

                return this.RedirectToAction(nameof(Index));
            }
            catch (Exception e)
            {
                Console.WriteLine(e.Message);
                return this.ExceptionCatchRedirect();
            }
        }

        [HttpGet]
        public async Task<IActionResult> Enable(string? id)
        {
            try
            {
                var enableResult = await this.costCenterService.EnableCostCenterAsync(id);
                if (enableResult == false)
                {
                    this.Response.StatusCode = 400;
                    return this.View(PathToBadRequestView);
                }

                return this.RedirectToAction(nameof(Index));
            }
            catch (Exception e)
            {
                Console.WriteLine(e.Message);
                return this.ExceptionCatchRedirect();
            }
        }

        [HttpGet]
        public async Task<IActionResult> Edit(string? id)
        {
            try
            {
                var model = await this.costCenterService.GetCostCenterForEditAsync(id);
                if (model == null)
                {
                    this.Response.StatusCode = 400;
                    return this.View(PathToBadRequestView);
                }

                model.Owners = await this.userService.GetUserDetailsAsync();
                return this.View(model);
            }
            catch (Exception e)
            {
                Console.WriteLine(e.Message);
                return this.ExceptionCatchRedirect();
            }
        }

        [HttpPost]
        public async Task<IActionResult> Edit(CostCenterEditInputModel model)
        {
            try
            {
                if (this.ModelState.IsValid == false)
                {
                    model.Owners = await this.userService.GetUserDetailsAsync();
                    return this.View(model);
                }

                var editResult = await this.costCenterService.EditCostCenterAsync(model);
                if (editResult == false)
                {
                    this.ModelState.AddModelError(string.Empty, CreateEditOverallErrorMessage);
                    model.Owners = await this.userService.GetUserDetailsAsync();
                    return this.View(model);
                }

                return this.RedirectToAction(nameof(Index));
            }
            catch (Exception e)
            {
                Console.WriteLine(e.Message);
                return this.ExceptionCatchRedirect();
            }
        }
    }
}

CostPilot.Web/Controllers/CostTypeController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.ModelBinding;

using CostPilot.Services.Core.Contracts;
using CostPilot.ViewModels.CostType;
using static CostPilot.Common.ValidationErrorMessages;
using static CostPilot.Common.ApplicationConstants;

namespace CostPilot.Web.Controllers
{
    public class CostTypeController : BaseAdminController
    {
        private readonly ICostTypeService costTypeService;

        public CostTypeController(ICostTypeService costTypeService)
        {
            this.costTypeService = costTypeService;
        }

        [HttpGet]
        public async Task<IActionResult> Index()
        {
            try
            {
                var model = await this.costTypeService.GetCostTypesAsync();
                return this.View(model);
            }
            catch (Exception e)
            {
                Console.WriteLine(e.Message);
                return this.ExceptionCatchRedirect();
            }
        }

        [HttpGet]
        public async Task<IActionResult> Create()
        {
            try
            {
                return this.View();
            }
            catch (Exception e)
            {
                Console.WriteLine(e.Message);
                return this.ExceptionCatchRedirect();
            }

        }

        [HttpPost]
        public async Task<IActionResult> Create(CostTypeCreateInputModel model)
        {
            try
            {
                if (this.ModelState.IsValid == false)
                {
                    return this.View(model);
                }

                var createResult = await this.costTypeService.CreateCostTypeAsync(model);
                if (createResult == false)
                {
                    this.ModelState.AddModelError(string.Empty, CreateEditOverallErrorMessage);
                    return this.View(model);
                }

                return this.RedirectToAction(nameof(Index));
            }
            catch (Exception e)
            {
                Console.WriteLine(e.Message);
                return this.ExceptionCatchRedirect();
            }
        }

        [HttpGet]
        public async Task<IActionResult> Disable(string? id)
        {
            try
            {
                var disableResult = await this.costTypeService.DisableCostTypeAsync(id);
                if (disableResult == false) 
                {
                    this.Response.StatusCode = 400;
                    return this.View(PathToBadRequestView);
                }

                return this.RedirectToAction(nameof(Index));
            }
            catch (Exception e)
            {
                Console.WriteLine(e.Message);
                return this.ExceptionCatchRedirect();
            }
        }

        [HttpGet]
        public async Task<IActionResult> Enable(string? id)
        {
            try
            {
                var enableResult = await this.costTypeService.EnableCostTypeAsync(id);
                if (enableResult == false)
                {
                    this.Response.StatusCode = 400;
                    return this.View(PathToBadRequestView);
                }

                return this.RedirectToAction(nameof(Index));
            }
            catch (Exception e)
            {
                Console.WriteLine(e.Message);
                return this.ExceptionCatchRedirect();
            }
        }

        [HttpGet]
        public async Task<IActionResult> Edit(string? id)
        {
            try
            {
                var model = await this.costTypeService.GetCostTypeForEditAsync(id);
                if (model == null)
                {
                    this.Response.StatusCode = 400;
                    return this.View(PathToBadRequestView);
                }

                return this.View(model);
            }
            catch (Exception e)
            {
                Console.WriteLine(e.Message);
                return this.ExceptionCatchRedirect();
            }
        }

        [HttpPost]
        public async Task<IActionResult> Edit(CostTypeEditInputModel model)
        {
            try
            {
                if (this.ModelState.IsValid == false)
                {
                    return this.View(model);
                }

                var editResult = await costTypeService.EditCostTypeAsync(model);
                if (editResult == false)
                {
                    this.ModelState.AddModelError(string.Empty, CreateEditOverallErrorMessage);
                    return this.View(model);
                }

                return this.RedirectToAction(nameof(Index));
            }
            catch (Exception e)
            {
                Console.WriteLine(e.Message);
                return this.ExceptionCatchRedirect();
            }
        }
    }
}

CostPilot.Web/Controllers/UserController.cs
using Microsoft.AspNetCore.Mvc;

using CostPilot.ViewModels.User;
using CostPilot.Services.Core.Contracts;
using static CostPilot.Common.ApplicationConstants;
using static CostPilot.Common.ValidationErrorMessages;

namespace CostPilot.Web.Controllers
{
    public class UserController : BaseAdminController
    {
        private readonly IUserService userService;
        private readonly IRoleService roleService;

        public UserController(IUserService userService,
            IRoleService roleService)
        {
            this.userService = userService;
            this.roleService = roleService;
        }

        [HttpGet]
        public async Task<IActionResult> Index()
        {
            try
            {
                var model = await this.userService.GetUserFullDetailsAsync();
                return View(model);
            }
            catch (Exception e)
            {
                Console.WriteLine(e.Message);
                return this.ExceptionCatchRedirect();
            }
        }

        [HttpGet]
        public async Task<IActionResult> AssignRole(string? id)
        {
            try
            {
                var model = await this.userService.GetUserForRoleAssignmentOrRemovalAsync(id);
                if (model == null)
                {
                    this.Response.StatusCode = 400;
                    return this.View(PathToBadRequestView);
                }

                model.Roles = await this.roleService.GetAllRolesExceptUserRolesAsync(model.Id);
                return View(model);
            }
            catch (Exception e)
            {
                Console.WriteLine(e.Message);
                return this.ExceptionCatchRedirect();
            }
        }

        [HttpPost]
        public async Task<IActionResult> AssignRole(UserRoleInputModel model)
        {
            try
            {
                if (this.ModelState.IsValid == false)
                {
                    model.Roles = await this.roleService.GetAllRolesExceptUserRolesAsync(model.Id);
                    return this.View(model);
                }

                var assignResult = await this.userService.AssignRoleToUserAsync(model);
                if (assignResult == false)
                {
                    this.ModelState.AddModelError(string.Empty, CreateEditOverallErrorMessage);
                    model.Roles = await this.roleService.GetAllRolesExceptUserRolesAsync(model.Id);
                    return this.View(model);
                }

                return this.RedirectToAction(nameof(Index));
            }
            catch (Exception e)
            {
                Console.WriteLine(e.Message);
                return this.ExceptionCatchRedirect();
            }
        }

        [HttpGet]
        public async Task<IActionResult> RemoveRole(string? id)
        {
            try
            {
                var model = await this.userService.GetUserForRoleAssignmentOrRemovalAsync(id);
                if (model == null)
                {
                    this.Response.StatusCode = 400;
                    return this.View(PathToBadRequestView);
                }

                model.Roles = await this.roleService.GetUserRolesAsync(model.Id);
                return View(model);
            }
            catch (Exception e)
            {
                Console.WriteLine(e.Message);
                return this.ExceptionCatchRedirect();
            }
        }

        [HttpPost]
        public async Task<IActionResult> RemoveRole(UserRoleInputModel model)
        {
            try
            {
                if (this.ModelState.IsValid == false)
                {
                    model.Roles = await this.roleService.GetUserRolesAsync(model.Id);
                    return this.View(model);
                }

                var removeResult = await this.userService.RemoveRoleFromUserAsync(model);
                if (removeResult == false)
                {
                    this.ModelState.AddModelError(string.Empty, CreateEditOverallErrorMessage);
                    model.Roles = await this.roleService.GetUserRolesAsync(model.Id);
                    return this.View(model);
                }

                return this.RedirectToAction(nameof(Index));
            }
            catch (Exception e)
            {
                Console.WriteLine(e.Message);
                return this.ExceptionCatchRedirect();
            }
        }
    }
}

CostPilot.Web/Views/Shared/BadRequest.cshtml
@{
    ViewData["Title"] = "Bad Request";
}

<h1 class="text-danger">400 - Bad Request</h1>
<p>The request could not be processed due to invalid input or malformed data.</p>
<a asp-controller="Home" asp-action="Index" class="btn btn-primary ">Return to Home</a>

CostPilot.Web/Views/Shared/PageNotFound.cshtml
@{
    ViewData["Title"] = "Page Not Found";
}

<h1 class="text-danger">404 - Page Not Found</h1>
<p>The page you are looking for does not exist.</p>
<a asp-controller="Home" asp-action="Index" class="btn btn-primary ">Return to Home</a>

CostPilot.Web/Views/Shared/_Layout.cshtml
@using static CostPilot.Common.ApplicationConstants;

@{
    var currentYear = DateTime.UtcNow.Year;
    var footerNote = (ReleaseYear == currentYear) ?
    $"{ReleaseYear}" : $"{ReleaseYear}-{currentYear}";
}


<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"]</title>
    <link rel="stylesheet" href="~/css/bootstrap.min.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/CostPilot.Web.styles.css" asp-append-version="true" />
    <link href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.0.0-beta3/css/all.min.css" rel="stylesheet" />
</head>
<body>
    <header class="text-white">
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-primary border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">CostPilot</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        @if (User?.Identity?.IsAuthenticated ?? false)
                        {
                            if (User.IsInRole(AdminRole) == true)
                            {
                                <li class="nav-item dropdown">
                                    <a class="nav-link text-dark dropdown-toggle" data-bs-toggle="dropdown" href="#" role="button" aria-haspopup="true" aria-expanded="false">Master Data</a>
                                    <div class="dropdown-menu">
                                        <a class="dropdown-item" asp-area="" asp-controller="CostCenter" asp-action="Index">Cost Centers</a>
                                        <div class="dropdown-divider"></div>
                                        <a class="dropdown-item" asp-area="" asp-controller="CostType" asp-action="Index">Cost Types</a>
                                        <div class="dropdown-divider"></div>
                                        <a class="dropdown-item" asp-area="" asp-controller="CostStatus" asp-action="Index">Cost Statuses</a>
                                        <div class="dropdown-divider"></div>
                                        <a class="dropdown-item" asp-area="" asp-controller="CostCurrency" asp-action="Index">Cost Currencies</a>
                                    </div>
                                </li>
                                <li class="nav-item">
                                    <a class="nav-link text-dark" asp-area="" asp-controller="User" asp-action="Index">Users</a>
                                </li>
                            }
                        }
                        @if (User?.Identity?.IsAuthenticated ?? false)
                        {
                            if (User.IsInRole(UserRole) == true)
                            {
                                <li class="nav-item dropdown">
                                    <a class="nav-link text-dark dropdown-toggle" data-bs-toggle="dropdown" href="#" role="button" aria-haspopup="true" aria-expanded="false">Requests</a>
                                    <div class="dropdown-menu">
                                        <a class="dropdown-item" asp-area="" asp-controller="CostRequest" asp-action="Create">Create New Request</a>
                                        <div class="dropdown-divider"></div>
                                        <a class="dropdown-item" asp-area="" asp-controller="CostRequest" asp-action="Index">My Requests</a>
                                    </div>
                                </li>
                                <li class="nav-item dropdown">
                                    <a class="nav-link text-dark dropdown-toggle" data-bs-toggle="dropdown" href="#" role="button" aria-haspopup="true" aria-expanded="false">Approvals</a>
                                    <div class="dropdown-menu">
                                        <a class="dropdown-item" asp-area="" asp-controller="CostRequest" asp-action="ForApproval">Pending Approvals</a>
                                        <div class="dropdown-divider"></div>
                                        <a class="dropdown-item" asp-area="" asp-controller="CostRequest" asp-action="AfterDecision">Approval History</a>
                                    </div>
                                </li>
                            }
                        }
                        @if (User?.Identity?.IsAuthenticated ?? false)
                        {
                            if (User.IsInRole(AnalystRole) == true)
                            {
                                <li class="nav-item">
                                    <a class="nav-link text-dark" asp-area="" asp-controller="CostRequest" asp-action="Dashboard">Dashboard</a>
                                </li>
                            }
                        }
                    </ul>
                    <partial name="_LoginPartial" />
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer bg-primary text-dark">
        <div class="container">
            &copy; @footerNote - CostPilot</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>