CostPilot.Web/Controllers/CostCurrencyController.cs
using Microsoft.AspNetCore.Mvc;

using CostPilot.Services.Core.Contracts;
using CostPilot.ViewModels.CostCurrency;
using static CostPilot.Common.ValidationErrorMessages;
using static CostPilot.Common.ApplicationConstants;

namespace CostPilot.Web.Controllers
{
    public class CostCurrencyController : BaseAdminController
    {
        private readonly ICostCurrencyService costCurrencyService;

        public CostCurrencyController(ICostCurrencyService costCurrencyService)
        {
            this.costCurrencyService = costCurrencyService;
        }

        [HttpGet]
        public async Task<IActionResult> Index()
        {
            try
            {
                var model = await this.costCurrencyService.GetCostCurrenciesAsync();
                return this.View(model);
            }
            catch (Exception e)
            {
                Console.WriteLine(e.Message);
                return this.ExceptionCatchRedirect();
            }
        }

        [HttpGet]
        public async Task<IActionResult> Create()
        {
            try
            {
                return this.View();
            }
            catch (Exception e)
            {
                Console.WriteLine(e.Message);
                return this.ExceptionCatchRedirect();
            }
        }

        [HttpPost]
        public async Task<IActionResult> Create(CostCurrencyCreateInputModel model)
        {
            try
            {
                if (this.ModelState.IsValid == false)
                {
                    return this.View(model);
                }

                var createResult = await this.costCurrencyService.CreateCostCurrencyAsync(model);
                if (createResult == false)
                {
                    this.ModelState.AddModelError(string.Empty, CreateEditOverallErrorMessage);
                    return this.View(model);
                }

                return this.RedirectToAction(nameof(Index));
            }
            catch (Exception e)
            {
                Console.WriteLine(e.Message);
                return this.ExceptionCatchRedirect();
            }
        }

        [HttpGet]
        public async Task<IActionResult> Disable(string? id)
        {
            try
            {
                var disableResult = await this.costCurrencyService.DisableCostCurrencyAsync(id);
                if (disableResult == false)
                {
                    this.Response.StatusCode = 400;
                    return this.View(PathToBadRequestView);
                }

                return this.RedirectToAction(nameof(Index));
            }
            catch (Exception e)
            {
                Console.WriteLine(e.Message);
                return this.ExceptionCatchRedirect();
            }
        }

        [HttpGet]
        public async Task<IActionResult> Enable(string? id)
        {
            try
            {
                var enableResult = await this.costCurrencyService.EnableCostCurrencyAsync(id);
                if (enableResult == false)
                {
                    this.Response.StatusCode = 400;
                    return this.View(PathToBadRequestView);
                }

                return this.RedirectToAction(nameof(Index));
            }
            catch (Exception e)
            {
                Console.WriteLine(e.Message);
                return this.ExceptionCatchRedirect();
            }
        }

        [HttpGet]
        public async Task<IActionResult> Edit(string? id)
        {
            try
            {
                var model = await this.costCurrencyService.GetCostCurrencyForEditAsync(id);
                if (model == null)
                {
                    this.Response.StatusCode = 400;
                    return this.View(PathToBadRequestView);
                }

                return this.View(model);
            }
            catch (Exception e)
            {
                Console.WriteLine(e.Message);
                return this.ExceptionCatchRedirect();
            }
        }

        [HttpPost]
        public async Task<IActionResult> Edit(CostCurrencyEditInputModel model)
        {
            try
            {
                if (this.ModelState.IsValid == false)
                {
                    return this.View(model);
                }

                var editResult = await this.costCurrencyService.EditCostCurrencyAsync(model);
                if (editResult == false)
                {
                    this.ModelState.AddModelError(string.Empty, CreateEditOverallErrorMessage);
                    return this.View(model);
                }

                return this.RedirectToAction(nameof(Index));
            }
            catch (Exception e)
            {
                Console.WriteLine(e.Message);
                return this.ExceptionCatchRedirect();
            }
        }
    }
}

CostPilot.Web/Views/CostCurrency/Create.cshtml
@using CostPilot.ViewModels.CostCurrency
@model CostCurrencyCreateInputModel

@{
    ViewData["Title"] = "Create New Cost Currency";
}

<h2 class="text-center">@ViewData["Title"]</h2>
<hr />

<div asp-validation-summary="ModelOnly" class="validation-summary-errors text-danger text-center"></div>

<div class="row">
    <div class="col-sm-12 offset-lg-2 col-lg-8 offset-xl-3 col-xl-6">
        <form asp-controller="CostCurrency" asp-action="Create" method="post">
            <div class="mb-2">
                <label asp-for="@Model.Code" class="form-label-add-edit">Code</label>
                <input asp-for="@Model.Code" class="form-control" aria-required="false" placeholder="Please enter cost currency code" />
                <span asp-validation-for="@Model.Code" class="text-danger"></span>
            </div>

            <div class="mb-2">
                <button class="btn btn-success btn-dark-text w-100 py-2 fw-bold rounded" type="submit">
                    <i class="fas fa-save"></i> Save
                </button>
            </div>
        </form>

        <div class="mb-2">
            <a asp-controller="CostCurrency" asp-action="Index" class="btn btn-secondary btn-dark-text w-100 py-2 fw-bold rounded">
                <i class="fa-solid fa-xmark"></i> Cancel
            </a>
        </div>
    </div>
</div>

CostPilot.Web/Views/CostCurrency/Edit.cshtml
@using CostPilot.ViewModels.CostCurrency
@model CostCurrencyEditInputModel

@{
    ViewData["Title"] = "Edit Cost Currency";
}

<h2 class="text-center">@ViewData["Title"]</h2>
<hr />

<div asp-validation-summary="ModelOnly" class="validation-summary-errors text-danger text-center"></div>

<div class="row">
    <div class="col-sm-12 offset-lg-2 col-lg-8 offset-xl-3 col-xl-6">
        <form asp-controller="CostCurrency" asp-action="Edit" method="post">
            <input type="hidden" asp-for="@Model.Id" />

            <div class="mb-2">
                <label asp-for="@Model.Code" class="form-label-add-edit">Code</label>
                <input asp-for="@Model.Code" class="form-control" aria-required="true" placeholder="Please enter cost currency code" />
                <span asp-validation-for="@Model.Code" class="text-danger"></span>
            </div>

            <div class="mb-2">
                <button class="btn btn-success btn-dark-text w-100 py-2 fw-bold rounded" type="submit">
                    <i class="fas fa-save"></i> Update
                </button>
            </div>
        </form>

        <div class="mb-2">
            <a asp-controller="CostCurrency" asp-action="Index" class="btn btn-secondary btn-dark-text w-100 py-2 fw-bold rounded">
                <i class="fa-solid fa-xmark"></i> Cancel
            </a>
        </div>
    </div>
</div>

CostPilot.Web/Views/CostCurrency/Index.cshtml
@using CostPilot.ViewModels.CostCurrency
@model IEnumerable<CostCurrencyIndexViewModel>

@{
    ViewData["Title"] = "Cost Currencies";
}

<h2 class="text-center">@ViewData["Title"]</h2>

<p class="text-center">
    <a asp-controller="CostCurrency" asp-action="Create" class="btn btn-success">Create New Cost Currency</a>
</p>
<hr />

@if (Model == null || Model.Any() == false)
{
    <div class="text-center mt-5">
        <h4>You don't have any cost currencies assigned yet!</h4>
        <p class="text-muted">Start creating and save your cost currencies.</p>
    </div>
}
else
{
    <div class="table-responsive" style="max-height: 400px; overflow-y: auto;">
        <table class="table table-striped">
            <thead>
                <tr>
                    <th style="position: sticky; top: 0; background-color: darkslategrey; z-index: 1;">Code</th>
                    <th style="position: sticky; top: 0; background-color: darkslategrey; z-index: 1;">Obsolete</th>
                    <th style="position: sticky; top: 0; background-color: darkslategrey; z-index: 1;">Actions</th>
                </tr>
            </thead>
            <tbody>
                @foreach (var costCurrency in Model)
                {
                    <tr>
                        <td>@costCurrency.Code</td>
                        <td>@costCurrency.IsObsolete</td>
                        <td>
                            <a asp-controller="CostCurrency" asp-action="Edit" asp-route-id="@costCurrency.Id" class="btn btn-sm btn-primary">Edit</a>
                            <a asp-controller="CostCurrency" asp-action="Disable" asp-route-id="@costCurrency.Id" class="btn btn-sm btn-danger">Disable</a>
                            <a asp-controller="CostCurrency" asp-action="Enable" asp-route-id="@costCurrency.Id" class="btn btn-sm btn-light">Enable</a>
                        </td>
                    </tr>
                }
            </tbody>
        </table>
    </div>
}